import type { Metadata } from "next";
import { Raleway, Petrona  } from "next/font/google";
import "./globals.css";

const raleway = Raleway({ 
  subsets: ["latin"],
  variable: '--font-raleway',
});
const petrona = Petrona({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FTCC - Community of Filipino tech professionals in Canberra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"${raleway.variable} scroll-smooth"}>
      <body className={petrona.className}>{children}</body>
    </html>
  );
}
